### ISSUE TITLE
Please use system() to suppress the screen flickering

### ISSUE THREAD

**Issue by itchyny** [junegunn/vim-github-dashboard#16]
In `s:open_url(url)`, you use `:silent! [command]` and redraw the screen. It causes the screen flickering. You can use the `system()` function to fix this issue.

**Comment by junegunn** [comment]
Hi, thanks for the comment. But the use of `!` is intentional to support external programs like `elinks` for opening the links. (https://github.com/junegunn/vim-github-dashboard/commit/2053f26)

```vim
let g:github_dashboard['open_command'] = 'elinks'
```

Maybe we could use `system()` instead only when `open_command` is not defined. Feel free to send me a PR if the flickering bothers you, thanks!
